export const QUESTIONS_ES: string[] = [
  '¿Qué tan seguro estás de que tu hijo ha consumido drogas, alcohol u otras sustancias?',
  '¿Con qué frecuencia sospechas que puede estar ocurriendo consumo de sustancias?',
  '¿Has notado secretismo, mentiras o evasión cuando intentas hablar de lo que te preocupa?',
  '¿Con qué frecuencia tu hijo pasa tiempo en entornos donde puede haber sustancias?',
  '¿Qué tan intensos son los conflictos entre tú y tu hijo respecto al comportamiento o las reglas?',
  '¿Qué tan preparado te sientes para confrontar a tu hijo sobre tus preocupaciones de consumo?',
  '¿Qué tan consistentes son las consecuencias cuando se rompen las reglas?',
  '¿Con qué frecuencia dudas si estás reaccionando de más o de menos?',
  '¿Has notado cambios importantes de ánimo, aislamiento o conductas agresivas?',
  '¿Qué tan preocupado estás por la seguridad de tu hijo (al conducir, entornos de riesgo, etc.)?',
  '¿Qué tan alineados están los cuidadores o co-padres al responder a esta situación?',
  '¿Con qué frecuencia tu hijo pasa tiempo con compañeros que consideras una mala influencia?',
  '¿Qué tan cómodo se siente tu hijo al hablar de estrés, ansiedad o dolor emocional?',
  '¿Con qué frecuencia monitoreas dónde está y qué hace tu hijo?',
  '¿Qué tan apoyado te sientes por el personal escolar o profesionales de la comunidad?',
  '¿Has buscado orientación con un terapeuta, consejero o proveedor de tratamiento?',
  '¿Con qué frecuencia te sientes agotado, con miedo o abrumado por la situación?',
  '¿Qué tan claro tienes el plan de próximos pasos si el consumo continúa?',
  '¿Con qué frecuencia tu hijo asume responsabilidad por su comportamiento?',
  '¿Cuánta estructura existe actualmente en la rutina diaria de tu hijo?',
  '¿Qué tan seguro estás de que el ambiente en casa desalienta el consumo de sustancias?',
  '¿Qué tan preparado te sientes para establecer límites firmes pero con apoyo?',
  '¿Con qué frecuencia te preocupan las consecuencias a largo plazo si los patrones continúan?',
  '¿Qué tan listo estás para actuar con decisión y proteger el bienestar de tu hijo?',
];
